
import React from 'react';

const HomePage: React.FC = () => {
  return (
    <div>
      <p className="text-white"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dignissim, massa quis efficitur consequat, nibh lorem ultrices dolor, et feugiat lacus neque in neque. Morbi ultrices maximus massa eget auctor. Sed ut viverra dui. Morbi pretium sodales sapien sed dignissim. Mauris laoreet feugiat nulla, nec elementum tortor sagittis et. Sed convallis elit vel turpis finibus, ac pretium massa rhoncus. Donec scelerisque elementum tincidunt. Maecenas ac ligula et diam iaculis luctus in in purus. Praesent finibus tellus a metus ornare elementum. Curabitur dignissim interdum commodo. Pellentesque ut enim ac nibh porttitor efficitur. Aenean eleifend efficitur felis, ut aliquet mauris semper a. Donec viverra tellus sapien, a vehicula eros malesuada vel.

Pellentesque ut magna vitae sem aliquam viverra at eget massa. Phasellus finibus pretium egestas. Sed ut hendrerit nibh, vitae ultrices sapien. Fusce consequat sagittis felis, non lacinia elit interdum id. Praesent velit augue, fringilla at nisi vel, volutpat vulputate libero. Nulla lectus est, viverra eu suscipit a, rutrum sit amet arcu. Proin id ipsum nibh.

In lobortis nisi non dui blandit, in cursus arcu mattis. Nam et orci et urna imperdiet elementum at ut sem. Vivamus quis metus accumsan, ultricies nunc in, efficitur justo. Sed auctor gravida ligula, in bibendum sapien hendrerit non. Aenean varius sodales neque, molestie eleifend lectus vehicula vel. In facilisis nibh egestas augue egestas, at mollis sem viverra. Pellentesque tempor, lacus eu eleifend dapibus, tortor urna ultrices metus, et euismod enim nisi ut libero. Aliquam at leo lorem.

Phasellus tempus odio sed varius elementum. Phasellus purus orci, lobortis ut rhoncus scelerisque, vehicula et mauris. Phasellus eu odio commodo risus varius varius quis a quam. Vivamus orci magna, placerat sit amet nisi ut, semper vulputate neque. In tristique id libero ac ultricies. Nulla tempor nec augue eget ullamcorper. Integer consectetur metus eu odio maximus faucibus. Duis non porttitor dolor. Pellentesque dictum sapien orci, eu ornare sapien placerat vitae.

Vestibulum dictum at sem eget sodales. Phasellus lorem arcu, tristique sit amet nunc et, tempus vulputate nunc. Fusce lacinia aliquet hendrerit. Praesent vestibulum tincidunt ipsum ut consectetur. Proin pellentesque eu quam et accumsan. Maecenas eget enim sed arcu sodales lobortis quis quis quam. Praesent elementum aliquam libero at feugiat. Cras ac dictum justo. Pellentesque commodo erat ligula, vitae imperdiet diam aliquet ut. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras aliquam lectus vitae odio rhoncus, id mollis nisl euismod.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dignissim, massa quis efficitur consequat, nibh lorem ultrices dolor, et feugiat lacus neque in neque. Morbi ultrices maximus massa eget auctor. Sed ut viverra dui. Morbi pretium sodales sapien sed dignissim. Mauris laoreet feugiat nulla, nec elementum tortor sagittis et. Sed convallis elit vel turpis finibus, ac pretium massa rhoncus. Donec scelerisque elementum tincidunt. Maecenas ac ligula et diam iaculis luctus in in purus. Praesent finibus tellus a metus ornare elementum. Curabitur dignissim interdum commodo. Pellentesque ut enim ac nibh porttitor efficitur. Aenean eleifend efficitur felis, ut aliquet mauris semper a. Donec viverra tellus sapien, a vehicula eros malesuada vel.

Pellentesque ut magna vitae sem aliquam viverra at eget massa. Phasellus finibus pretium egestas. Sed ut hendrerit nibh, vitae ultrices sapien. Fusce consequat sagittis felis, non lacinia elit interdum id. Praesent velit augue, fringilla at nisi vel, volutpat vulputate libero. Nulla lectus est, viverra eu suscipit a, rutrum sit amet arcu. Proin id ipsum nibh.

In lobortis nisi non dui blandit, in cursus arcu mattis. Nam et orci et urna imperdiet elementum at ut sem. Vivamus quis metus accumsan, ultricies nunc in, efficitur justo. Sed auctor gravida ligula, in bibendum sapien hendrerit non. Aenean varius sodales neque, molestie eleifend lectus vehicula vel. In facilisis nibh egestas augue egestas, at mollis sem viverra. Pellentesque tempor, lacus eu eleifend dapibus, tortor urna ultrices metus, et euismod enim nisi ut libero. Aliquam at leo lorem.

Phasellus tempus odio sed varius elementum. Phasellus purus orci, lobortis ut rhoncus scelerisque, vehicula et mauris. Phasellus eu odio commodo risus varius varius quis a quam. Vivamus orci magna, placerat sit amet nisi ut, semper vulputate neque. In tristique id libero ac ultricies. Nulla tempor nec augue eget ullamcorper. Integer consectetur metus eu odio maximus faucibus. Duis non porttitor dolor. Pellentesque dictum sapien orci, eu ornare sapien placerat vitae.

Vestibulum dictum at sem eget sodales. Phasellus lorem arcu, tristique sit amet nunc et, tempus vulputate nunc. Fusce lacinia aliquet hendrerit. Praesent vestibulum tincidunt ipsum ut consectetur. Proin pellentesque eu quam et accumsan. Maecenas eget enim sed arcu sodales lobortis quis quis quam. Praesent elementum aliquam libero at feugiat. Cras ac dictum justo. Pellentesque commodo erat ligula, vitae imperdiet diam aliquet ut. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras aliquam lectus vitae odio rhoncus, id mollis nisl euismod.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dignissim, massa quis efficitur consequat, nibh lorem ultrices dolor, et feugiat lacus neque in neque. Morbi ultrices maximus massa eget auctor. Sed ut viverra dui. Morbi pretium sodales sapien sed dignissim. Mauris laoreet feugiat nulla, nec elementum tortor sagittis et. Sed convallis elit vel turpis finibus, ac pretium massa rhoncus. Donec scelerisque elementum tincidunt. Maecenas ac ligula et diam iaculis luctus in in purus. Praesent finibus tellus a metus ornare elementum. Curabitur dignissim interdum commodo. Pellentesque ut enim ac nibh porttitor efficitur. Aenean eleifend efficitur felis, ut aliquet mauris semper a. Donec viverra tellus sapien, a vehicula eros malesuada vel.

Pellentesque ut magna vitae sem aliquam viverra at eget massa. Phasellus finibus pretium egestas. Sed ut hendrerit nibh, vitae ultrices sapien. Fusce consequat sagittis felis, non lacinia elit interdum id. Praesent velit augue, fringilla at nisi vel, volutpat vulputate libero. Nulla lectus est, viverra eu suscipit a, rutrum sit amet arcu. Proin id ipsum nibh.

In lobortis nisi non dui blandit, in cursus arcu mattis. Nam et orci et urna imperdiet elementum at ut sem. Vivamus quis metus accumsan, ultricies nunc in, efficitur justo. Sed auctor gravida ligula, in bibendum sapien hendrerit non. Aenean varius sodales neque, molestie eleifend lectus vehicula vel. In facilisis nibh egestas augue egestas, at mollis sem viverra. Pellentesque tempor, lacus eu eleifend dapibus, tortor urna ultrices metus, et euismod enim nisi ut libero. Aliquam at leo lorem.

Phasellus tempus odio sed varius elementum. Phasellus purus orci, lobortis ut rhoncus scelerisque, vehicula et mauris. Phasellus eu odio commodo risus varius varius quis a quam. Vivamus orci magna, placerat sit amet nisi ut, semper vulputate neque. In tristique id libero ac ultricies. Nulla tempor nec augue eget ullamcorper. Integer consectetur metus eu odio maximus faucibus. Duis non porttitor dolor. Pellentesque dictum sapien orci, eu ornare sapien placerat vitae.

Vestibulum dictum at sem eget sodales. Phasellus lorem arcu, tristique sit amet nunc et, tempus vulputate nunc. Fusce lacinia aliquet hendrerit. Praesent vestibulum tincidunt ipsum ut consectetur. Proin pellentesque eu quam et accumsan. Maecenas eget enim sed arcu sodales lobortis quis quis quam. Praesent elementum aliquam libero at feugiat. Cras ac dictum justo. Pellentesque commodo erat ligula, vitae imperdiet diam aliquet ut. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras aliquam lectus vitae odio rhoncus, id mollis nisl euismod.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dignissim, massa quis efficitur consequat, nibh lorem ultrices dolor, et feugiat lacus neque in neque. Morbi ultrices maximus massa eget auctor. Sed ut viverra dui. Morbi pretium sodales sapien sed dignissim. Mauris laoreet feugiat nulla, nec elementum tortor sagittis et. Sed convallis elit vel turpis finibus, ac pretium massa rhoncus. Donec scelerisque elementum tincidunt. Maecenas ac ligula et diam iaculis luctus in in purus. Praesent finibus tellus a metus ornare elementum. Curabitur dignissim interdum commodo. Pellentesque ut enim ac nibh porttitor efficitur. Aenean eleifend efficitur felis, ut aliquet mauris semper a. Donec viverra tellus sapien, a vehicula eros malesuada vel.

Pellentesque ut magna vitae sem aliquam viverra at eget massa. Phasellus finibus pretium egestas. Sed ut hendrerit nibh, vitae ultrices sapien. Fusce consequat sagittis felis, non lacinia elit interdum id. Praesent velit augue, fringilla at nisi vel, volutpat vulputate libero. Nulla lectus est, viverra eu suscipit a, rutrum sit amet arcu. Proin id ipsum nibh.

In lobortis nisi non dui blandit, in cursus arcu mattis. Nam et orci et urna imperdiet elementum at ut sem. Vivamus quis metus accumsan, ultricies nunc in, efficitur justo. Sed auctor gravida ligula, in bibendum sapien hendrerit non. Aenean varius sodales neque, molestie eleifend lectus vehicula vel. In facilisis nibh egestas augue egestas, at mollis sem viverra. Pellentesque tempor, lacus eu eleifend dapibus, tortor urna ultrices metus, et euismod enim nisi ut libero. Aliquam at leo lorem.

Phasellus tempus odio sed varius elementum. Phasellus purus orci, lobortis ut rhoncus scelerisque, vehicula et mauris. Phasellus eu odio commodo risus varius varius quis a quam. Vivamus orci magna, placerat sit amet nisi ut, semper vulputate neque. In tristique id libero ac ultricies. Nulla tempor nec augue eget ullamcorper. Integer consectetur metus eu odio maximus faucibus. Duis non porttitor dolor. Pellentesque dictum sapien orci, eu ornare sapien placerat vitae.

Vestibulum dictum at sem eget sodales. Phasellus lorem arcu, tristique sit amet nunc et, tempus vulputate nunc. Fusce lacinia aliquet hendrerit. Praesent vestibulum tincidunt ipsum ut consectetur. Proin pellentesque eu quam et accumsan. Maecenas eget enim sed arcu sodales lobortis quis quis quam. Praesent elementum aliquam libero at feugiat. Cras ac dictum justo. Pellentesque commodo erat ligula, vitae imperdiet diam aliquet ut. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras aliquam lectus vitae odio rhoncus, id mollis nisl euismod.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dignissim, massa quis efficitur consequat, nibh lorem ultrices dolor, et feugiat lacus neque in neque. Morbi ultrices maximus massa eget auctor. Sed ut viverra dui. Morbi pretium sodales sapien sed dignissim. Mauris laoreet feugiat nulla, nec elementum tortor sagittis et. Sed convallis elit vel turpis finibus, ac pretium massa rhoncus. Donec scelerisque elementum tincidunt. Maecenas ac ligula et diam iaculis luctus in in purus. Praesent finibus tellus a metus ornare elementum. Curabitur dignissim interdum commodo. Pellentesque ut enim ac nibh porttitor efficitur. Aenean eleifend efficitur felis, ut aliquet mauris semper a. Donec viverra tellus sapien, a vehicula eros malesuada vel.

Pellentesque ut magna vitae sem aliquam viverra at eget massa. Phasellus finibus pretium egestas. Sed ut hendrerit nibh, vitae ultrices sapien. Fusce consequat sagittis felis, non lacinia elit interdum id. Praesent velit augue, fringilla at nisi vel, volutpat vulputate libero. Nulla lectus est, viverra eu suscipit a, rutrum sit amet arcu. Proin id ipsum nibh.

In lobortis nisi non dui blandit, in cursus arcu mattis. Nam et orci et urna imperdiet elementum at ut sem. Vivamus quis metus accumsan, ultricies nunc in, efficitur justo. Sed auctor gravida ligula, in bibendum sapien hendrerit non. Aenean varius sodales neque, molestie eleifend lectus vehicula vel. In facilisis nibh egestas augue egestas, at mollis sem viverra. Pellentesque tempor, lacus eu eleifend dapibus, tortor urna ultrices metus, et euismod enim nisi ut libero. Aliquam at leo lorem.

Phasellus tempus odio sed varius elementum. Phasellus purus orci, lobortis ut rhoncus scelerisque, vehicula et mauris. Phasellus eu odio commodo risus varius varius quis a quam. Vivamus orci magna, placerat sit amet nisi ut, semper vulputate neque. In tristique id libero ac ultricies. Nulla tempor nec augue eget ullamcorper. Integer consectetur metus eu odio maximus faucibus. Duis non porttitor dolor. Pellentesque dictum sapien orci, eu ornare sapien placerat vitae.

Vestibulum dictum at sem eget sodales. Phasellus lorem arcu, tristique sit amet nunc et, tempus vulputate nunc. Fusce lacinia aliquet hendrerit. Praesent vestibulum tincidunt ipsum ut consectetur. Proin pellentesque eu quam et accumsan. Maecenas eget enim sed arcu sodales lobortis quis quis quam. Praesent elementum aliquam libero at feugiat. Cras ac dictum justo. Pellentesque commodo erat ligula, vitae imperdiet diam aliquet ut. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras aliquam lectus vitae odio rhoncus, id mollis nisl euismod.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dignissim, massa quis efficitur consequat, nibh lorem ultrices dolor, et feugiat lacus neque in neque. Morbi ultrices maximus massa eget auctor. Sed ut viverra dui. Morbi pretium sodales sapien sed dignissim. Mauris laoreet feugiat nulla, nec elementum tortor sagittis et. Sed convallis elit vel turpis finibus, ac pretium massa rhoncus. Donec scelerisque elementum tincidunt. Maecenas ac ligula et diam iaculis luctus in in purus. Praesent finibus tellus a metus ornare elementum. Curabitur dignissim interdum commodo. Pellentesque ut enim ac nibh porttitor efficitur. Aenean eleifend efficitur felis, ut aliquet mauris semper a. Donec viverra tellus sapien, a vehicula eros malesuada vel.

Pellentesque ut magna vitae sem aliquam viverra at eget massa. Phasellus finibus pretium egestas. Sed ut hendrerit nibh, vitae ultrices sapien. Fusce consequat sagittis felis, non lacinia elit interdum id. Praesent velit augue, fringilla at nisi vel, volutpat vulputate libero. Nulla lectus est, viverra eu suscipit a, rutrum sit amet arcu. Proin id ipsum nibh.

In lobortis nisi non dui blandit, in cursus arcu mattis. Nam et orci et urna imperdiet elementum at ut sem. Vivamus quis metus accumsan, ultricies nunc in, efficitur justo. Sed auctor gravida ligula, in bibendum sapien hendrerit non. Aenean varius sodales neque, molestie eleifend lectus vehicula vel. In facilisis nibh egestas augue egestas, at mollis sem viverra. Pellentesque tempor, lacus eu eleifend dapibus, tortor urna ultrices metus, et euismod enim nisi ut libero. Aliquam at leo lorem.

Phasellus tempus odio sed varius elementum. Phasellus purus orci, lobortis ut rhoncus scelerisque, vehicula et mauris. Phasellus eu odio commodo risus varius varius quis a quam. Vivamus orci magna, placerat sit amet nisi ut, semper vulputate neque. In tristique id libero ac ultricies. Nulla tempor nec augue eget ullamcorper. Integer consectetur metus eu odio maximus faucibus. Duis non porttitor dolor. Pellentesque dictum sapien orci, eu ornare sapien placerat vitae.

Vestibulum dictum at sem eget sodales. Phasellus lorem arcu, tristique sit amet nunc et, tempus vulputate nunc. Fusce lacinia aliquet hendrerit. Praesent vestibulum tincidunt ipsum ut consectetur. Proin pellentesque eu quam et accumsan. Maecenas eget enim sed arcu sodales lobortis quis quis quam. Praesent elementum aliquam libero at feugiat. Cras ac dictum justo. Pellentesque commodo erat ligula, vitae imperdiet diam aliquet ut. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras aliquam lectus vitae odio rhoncus, id mollis nisl euismod.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dignissim, massa quis efficitur consequat, nibh lorem ultrices dolor, et feugiat lacus neque in neque. Morbi ultrices maximus massa eget auctor. Sed ut viverra dui. Morbi pretium sodales sapien sed dignissim. Mauris laoreet feugiat nulla, nec elementum tortor sagittis et. Sed convallis elit vel turpis finibus, ac pretium massa rhoncus. Donec scelerisque elementum tincidunt. Maecenas ac ligula et diam iaculis luctus in in purus. Praesent finibus tellus a metus ornare elementum. Curabitur dignissim interdum commodo. Pellentesque ut enim ac nibh porttitor efficitur. Aenean eleifend efficitur felis, ut aliquet mauris semper a. Donec viverra tellus sapien, a vehicula eros malesuada vel.

Pellentesque ut magna vitae sem aliquam viverra at eget massa. Phasellus finibus pretium egestas. Sed ut hendrerit nibh, vitae ultrices sapien. Fusce consequat sagittis felis, non lacinia elit interdum id. Praesent velit augue, fringilla at nisi vel, volutpat vulputate libero. Nulla lectus est, viverra eu suscipit a, rutrum sit amet arcu. Proin id ipsum nibh.

In lobortis nisi non dui blandit, in cursus arcu mattis. Nam et orci et urna imperdiet elementum at ut sem. Vivamus quis metus accumsan, ultricies nunc in, efficitur justo. Sed auctor gravida ligula, in bibendum sapien hendrerit non. Aenean varius sodales neque, molestie eleifend lectus vehicula vel. In facilisis nibh egestas augue egestas, at mollis sem viverra. Pellentesque tempor, lacus eu eleifend dapibus, tortor urna ultrices metus, et euismod enim nisi ut libero. Aliquam at leo lorem.

Phasellus tempus odio sed varius elementum. Phasellus purus orci, lobortis ut rhoncus scelerisque, vehicula et mauris. Phasellus eu odio commodo risus varius varius quis a quam. Vivamus orci magna, placerat sit amet nisi ut, semper vulputate neque. In tristique id libero ac ultricies. Nulla tempor nec augue eget ullamcorper. Integer consectetur metus eu odio maximus faucibus. Duis non porttitor dolor. Pellentesque dictum sapien orci, eu ornare sapien placerat vitae.

Vestibulum dictum at sem eget sodales. Phasellus lorem arcu, tristique sit amet nunc et, tempus vulputate nunc. Fusce lacinia aliquet hendrerit. Praesent vestibulum tincidunt ipsum ut consectetur. Proin pellentesque eu quam et accumsan. Maecenas eget enim sed arcu sodales lobortis quis quis quam. Praesent elementum aliquam libero at feugiat. Cras ac dictum justo. Pellentesque commodo erat ligula, vitae imperdiet diam aliquet ut. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras aliquam lectus vitae odio rhoncus, id mollis nisl euismod.</p>
      {/* <h1>Welcome to the Home Page</h1> */}
      {/* Add your content here */}
    </div>
  );
};

export default HomePage;
